name: Deploy Pages

on:
  push:
    branches:
      - main        # deploy preview site
    tags:
      - '*'         # deploy stable release site
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build site
        run: |
          echo "Building site from $GITHUB_REF"
          # e.g. npm install && npm run build

      - name: Organize output
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            mkdir -p public/preview
            mv public/* public/preview/ || true
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
